version: 2.1

workflows:
  test:
    jobs:
      - build-run-linux:
          context: hello-world-demos

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: master
    jobs:
    - build-run-linux:
        context: hello-world-demos

# This CI build ensures that the demo both compiles and works correctly. For the runtime test,
# we use an SDK key and flag key that are passed in via the CircleCI project configuration;
# the flag is configured to return a true value.

jobs:
  build-run-linux:
    docker:
      - image: cimg/python:3.5
    steps:
      - checkout
      - run:
          name: insert SDK key and flag key into demo code
          command: |
            sed -i.bak "s/sdk_key *= *\".*\"/sdk_key = \"${LD_HELLO_WORLD_SDK_KEY}\"/" test.py
            sed -i.bak "s/feature_flag_key *= *\".*\"/feature_flag_key = \"${LD_HELLO_WORLD_FLAG_KEY_WITH_TRUE_VALUE}\"/" test.py
      - run:
          name: Install dependencies
          command: pip install --user -r requirements.txt
      - run:
          name: Run hello
          command: python test.py | tee output.txt
      - run:
          name: Check output
          command: |
            grep "is True for this user" output.txt || (echo "Flag did not evaluate to expected true value" && exit 1)
